language: csharp
mono: none
sudo: required
dotnet: 2.2
dist: xenial

branches:
  only:
  - master
  - develop

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
    - DOTNET_CLI_TELEMETRY_OPTOUT=1
install:
  - dotnet restore

script: 
  - dotnet build
  - dotnet test FluentApiGenericRepository.Test/FluentApiGenericRepository.Test.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

after_script:
  - curl -s https://codecov.io/bash > codecov
  - chmod +x codecov
  - ./codecov -f "./FluentApiGenericRepository.Test/coverage.opencover.xml" -t $CODECOV_TOKEN
  - dotnet pack -c Release -p:PackageVersion=1.$TRAVIS_BUILD_NUMBER.0
  - cd ./FluentApiGenericRepository/bin/Release
  - dotnet nuget push FluentApiGenericRepository.1.$TRAVIS_BUILD_NUMBER.0 -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json
